baseURL = 'http://kwakelin.github.io/'
languageCode = 'en-gb'
title = 'Katie Wakelin'
theme = "ananke"
resourceDir = "../resources"

DefaultContentLanguage = "en"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "Katie Wakelin"
  favicon = "images/Victor_Hugo-Hunchback.jpg"
  # site_logo = "images/Victor_Hugo-Hunchback.jpg"
  description = "Illustation and Copywriting portfolio website"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3
  custom_css = ["custom.css"]
  mainSections = ["post"]
  recent_copy = "Blog Posts"

[params.ananke_socials.1]
name = "twitter"
url = "https://twitter.com/PanDimensions"

[params.ananke_socials.2]
name = "artstation"
url = "https://www.artstation.com/katiewakelin"
